# Generated by Django 2.1.5 on 2019-06-15 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='subject',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='classroom.Subject'),
            preserve_default=False,
        ),
    ]
