# Generated by Django 2.1.5 on 2019-06-15 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_instructor_subject'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instructor',
            options={},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={},
        ),
        migrations.AlterModelManagers(
            name='instructor',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='student',
            managers=[
            ],
        ),
    ]
