# Generated by Django 2.1.5 on 2019-06-15 13:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0004_auto_20190615_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='value',
            field=models.FloatField(default=0.5, validators=[django.core.validators.MinValueValidator(0.3), django.core.validators.MaxValueValidator(0.8)]),
        ),
        migrations.AlterField(
            model_name='question',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='classroom.Subject'),
        ),
    ]
