# Generated by Django 2.1.5 on 2019-06-16 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0005_auto_20190615_1311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='questions',
        ),
    ]
