# Generated by Django 2.1.5 on 2019-06-17 13:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0007_auto_20190617_0941'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('data', models.DateTimeField(default=datetime.datetime(2019, 6, 17, 13, 39, 22, 171720))),
                ('position', models.CharField(max_length=200)),
            ],
        ),
    ]
