# Generated by Django 2.0.1 on 2019-06-17 20:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0008_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 17, 20, 49, 12, 306212, tzinfo=utc)),
        ),
    ]
