# Generated by Django 2.1.5 on 2019-06-22 12:43

import classroom.models
import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0009_auto_20190617_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='chapter_num',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MinValueValidator(classroom.models.Question.get_chapter_num)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='difficulty',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(2), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='question',
            name='objective',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='subject',
            name='chapter_num',
            field=models.IntegerField(default='1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject',
            name='objective',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='subject',
            name='question_num_difficult',
            field=models.IntegerField(default='1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject',
            name='question_num_per_chapter1',
            field=models.IntegerField(default='1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject',
            name='question_num_ramining',
            field=models.IntegerField(default='1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject',
            name='question_num_understanding',
            field=models.IntegerField(default='1'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 22, 12, 42, 59, 18733, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='question',
            name='value',
            field=models.FloatField(default=0.5, validators=[django.core.validators.MinValueValidator(0.3), django.core.validators.MaxValueValidator(0.8)]),
        ),
    ]
