# Generated by Django 2.1.5 on 2019-06-22 12:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0011_auto_20190622_1244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='question_num_per_chapter1',
        ),
        migrations.AlterField(
            model_name='event',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 22, 12, 50, 59, 233841, tzinfo=utc)),
        ),
    ]
