# Generated by Django 2.1.5 on 2019-06-22 13:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0013_auto_20190622_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 22, 13, 14, 24, 984103, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='subject',
            name='question_num_difficult',
            field=models.IntegerField(default=1),
        ),
    ]
