# Generated by Django 2.1.5 on 2019-06-23 08:52

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0014_auto_20190622_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 23, 8, 52, 37, 656365, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='question',
            name='chapter_num',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)]),
        ),
        migrations.AlterField(
            model_name='question',
            name='difficulty',
            field=models.IntegerField(choices=[(1, 'difficult'), (2, 'simple')], default=1),
        ),
        migrations.AlterField(
            model_name='question',
            name='objective',
            field=models.IntegerField(choices=[(1, 'understanding'), (2, 'creative'), (3, 'remining')], default=1),
        ),
    ]
