# Generated by Django 2.1.5 on 2019-06-23 09:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0015_auto_20190623_0852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='objective',
        ),
        migrations.AlterField(
            model_name='event',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 23, 9, 43, 59, 824782, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='question',
            name='objective',
            field=models.IntegerField(choices=[(1, 'remining'), (2, 'understanding'), (3, 'creative')], default=1),
        ),
    ]
