# Generated by Django 2.1.5 on 2019-06-23 16:37

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0016_auto_20190623_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 23, 16, 37, 18, 151885, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='subject',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='classroom.Subject'),
        ),
    ]
